/**
 * @description: utility class for get the custom label values.
 * @author            : Ravi Sirigiri
 * @group             : 
 * @last modified on  : 04-30-2021
 * @last modified by  : Ravi Sirigiri
 * Modifications Log 
 * Ver   Date         Author          Modification
 * 1.0   01-06-2021   Ravi Sirigiri   Initial Version
**/
import { LightningElement , api } from 'lwc';
import  AGN_OAM_Website_Link from '@salesforce/label/c.AGN_OAM_Website_Link';
import  AGN_OAM_Mapping_2 from '@salesforce/label/c.AGN_OAM_Mapping_2';
import  AGN_OAM_Mapping_1 from '@salesforce/label/c.AGN_OAM_Mapping_1';
import  AGN_OAM_Distribution_ID from '@salesforce/label/c.AGN_OAM_Distribution_ID';
import  AGN_OAM_Additional_Comments from '@salesforce/label/c.AGN_OAM_Additional_Comments';
import  AGN_OAM_Company_Name_3 from '@salesforce/label/c.AGN_OAM_Company_Name_3';
import  AGN_OAM_Company_Name_2 from '@salesforce/label/c.AGN_OAM_Company_Name_2';
import  AGN_OAM_Address_Line_1 from '@salesforce/label/c.AGN_OAM_Address_Line_1';
import  AGN_OAM_Address_Line_1_1 from '@salesforce/label/c.AGN_OAM_Address_Line_1_1';
import  AGN_OAM_Bank_Account_Number from '@salesforce/label/c.AGN_OAM_Bank_Account_Number';
import  AGN_OAM_BanK_Name from '@salesforce/label/c.AGN_OAM_BanK_Name';
import  AGN_OAM_City from '@salesforce/label/c.AGN_OAM_City';
import  AGN_OAM_Company_Name from '@salesforce/label/c.AGN_OAM_Company_Name';
import  AGN_OAM_Body_Country from '@salesforce/label/c.AGN_OAM_Body_Country';
import  AGN_OAM_Department_Name from '@salesforce/label/c.AGN_OAM_Department_Name';
import  AGN_OAM_Email_1 from '@salesforce/label/c.AGN_OAM_Email_1';
import  AGN_OAM_Email from '@salesforce/label/c.AGN_OAM_Email';
import  AGN_OAM_First_Name from '@salesforce/label/c.AGN_OAM_First_Name';
import  AGN_OAM_IBAN from '@salesforce/label/c.AGN_OAM_IBAN';
import  AGN_OAM_Last_Name from '@salesforce/label/c.AGN_OAM_Last_Name';
import  AGN_OAM_Phone from '@salesforce/label/c.AGN_OAM_Phone';
import  AGN_OAM_Preferred_Communication from '@salesforce/label/c.AGN_OAM_Preferred_Communication';
import  AGN_OAM_Registration_License_Number from '@salesforce/label/c.AGN_OAM_Registration_License_Number';
import  AGN_OAM_Salutation from '@salesforce/label/c.AGN_OAM_Salutation';
import  AGN_OAM_Sort_Code from '@salesforce/label/c.AGN_OAM_Sort_Code';
import  AGN_OAM_State from '@salesforce/label/c.AGN_OAM_State';
import  AGN_OAM_SWIFT_BIC from '@salesforce/label/c.AGN_OAM_SWIFT_BIC';
import  AGN_OAM_Tax_Exempted from '@salesforce/label/c.AGN_OAM_Tax_Exempted';
import  AGN_OAM_Tax_Number from '@salesforce/label/c.AGN_OAM_Tax_Number';
import  AGN_OAM_Tax_Number_1 from '@salesforce/label/c.AGN_OAM_Tax_Number_1';
import  AGN_OAM_VAT_Number from '@salesforce/label/c.AGN_OAM_VAT_Number';
import  AGN_OAM_ZIP_Code from '@salesforce/label/c.AGN_OAM_ZIP_Code';
import  AGN_OAM_Additional_Shipping_Ins from '@salesforce/label/c.AGN_OAM_Additional_Shipping_Ins';
import  AGN_OAM_Customer_Group from '@salesforce/label/c.AGN_OAM_Customer_Group';
import  AGN_OAM_Contact_Person_Type from '@salesforce/label/c.AGN_OAM_Contact_Person_Type';
import  AGN_OAM_Gender from '@salesforce/label/c.AGN_OAM_Gender';
import  AGN_OAM_Language from '@salesforce/label/c.AGN_OAM_Language';
import  AGN_OAM_Enable_OAM_Portal_Access from '@salesforce/label/c.AGN_OAM_Enable_OAM_Portal_Access';
import  AGN_OAM_Name1 from '@salesforce/label/c.AGN_OAM_Name1';
import  AGN_OAM_Name2 from '@salesforce/label/c.AGN_OAM_Name2';
import  AGN_OAM_Name3 from '@salesforce/label/c.AGN_OAM_Name3';
import  AGN_OAM_SAP_Name_4 from '@salesforce/label/c.AGN_OAM_SAP_Name_4';
import  AGN_OAM_Shipping_Instruction from '@salesforce/label/c.AGN_OAM_Shipping_Instruction';
import  AGN_OAM_Sales_Text_1 from '@salesforce/label/c.AGN_OAM_Sales_Text_1';
import  AGN_OAM_Article_23_relevant from '@salesforce/label/c.AGN_OAM_Article_23_relevant';
import  AGN_OAM_Shipping_Instructions_AGN_c from '@salesforce/label/c.AGN_OAM_Shipping_Instructions_AGN_c';
import  AGN_OAM_SAP_SalesText_AGN_c from '@salesforce/label/c.AGN_OAM_SAP_SalesText_AGN_c';
import  AGN_OAM_First_Name_AGN from '@salesforce/label/c.AGN_OAM_First_Name_AGN';
import  AGN_OAM_Last_Name_2 from '@salesforce/label/c.AGN_OAM_Last_Name_2';
import  AGN_OAM_Phone_AGN from '@salesforce/label/c.AGN_OAM_Phone_AGN';
import  AGN_OAM_Shipping_Address from '@salesforce/label/c.AGN_OAM_Shipping_Address';
import  AGN_OAM_Billing_Address from '@salesforce/label/c.AGN_OAM_Billing_Address';
import  AGN_OAM_Registered_Address from '@salesforce/label/c.AGN_OAM_Registered_Address';
import  AGN_OAM_Basic_Information from '@salesforce/label/c.AGN_OAM_Basic_Information';
import  AGN_OAM_Fax from '@salesforce/label/c.AGN_OAM_Fax';
import  AGN_OAM_SED_SLI_Instructions from '@salesforce/label/c.AGN_OAM_SED_SLI_Instructions';
import  AGN_OAM_Public_Private from '@salesforce/label/c.AGN_OAM_Public_Private';
import  AGN_OAM_Default_Ship_To from '@salesforce/label/c.AGN_OAM_Default_Ship_To';
import  AGN_OAM_Default_Bill_To from '@salesforce/label/c.AGN_OAM_Default_Bill_To';
import  AGN_OAM_Body_PaymentMethod from '@salesforce/label/c.AGN_OAM_Body_PaymentMethod';
import  AGN_OAM_Tax_Classification from '@salesforce/label/c.AGN_OAM_Tax_Classification';
import  AGN_OAM_Price_Group from '@salesforce/label/c.AGN_OAM_Price_Group';
import  AGN_OAM_Price_List from '@salesforce/label/c.AGN_OAM_Price_List';
import  AGN_OAM_VAT from '@salesforce/label/c.AGN_OAM_VAT';
import  AGN_OAM_VAT_Number_1 from '@salesforce/label/c.AGN_OAM_VAT_Number_1';
import  AGN_OAM_CIP_Number from '@salesforce/label/c.AGN_OAM_CIP_Number';
import  AGN_OAM_MOH_Number from '@salesforce/label/c.AGN_OAM_MOH_Number';
import  AGN_OAM_Province from '@salesforce/label/c.AGN_OAM_Province';
import  AGN_OAM_Payment_Term from '@salesforce/label/c.AGN_OAM_Payment_Term';
import  AGN_OAM_CUU_Code from '@salesforce/label/c.AGN_OAM_CUU_Code';
import  AGN_OAM_VAT_Number_CL_HR_PH_VP from '@salesforce/label/c.AGN_OAM_VAT_Number_CL_HR_PH_VP';
import  AGN_OAM_Codice_Fiscal from '@salesforce/label/c.AGN_OAM_Codice_Fiscal';
import  AGN_OAM_Region from '@salesforce/label/c.AGN_OAM_Region';
import  AGN_OAM_VAT_Number_3 from '@salesforce/label/c.AGN_OAM_VAT_Number_3';
import  AGN_OAM_Tax_Office from '@salesforce/label/c.AGN_OAM_Tax_Office';
import  AGN_OAM_Sales_District from '@salesforce/label/c.AGN_OAM_Sales_District';
import  AGN_OAM_Phone_1 from '@salesforce/label/c.AGN_OAM_Phone_1';
import  AGN_OAM_District from '@salesforce/label/c.AGN_OAM_District';
import  AGN_OAM_State_License_Number from '@salesforce/label/c.AGN_OAM_State_License_Number';
import  AGN_OAM_Local_Title from '@salesforce/label/c.AGN_OAM_Local_Title';
import  AGN_OAM_Local_Name from '@salesforce/label/c.AGN_OAM_Local_Name';
import  AGN_OAM_Local_Name_2 from '@salesforce/label/c.AGN_OAM_Local_Name_2';
import  AGN_OAM_Local_Name_3 from '@salesforce/label/c.AGN_OAM_Local_Name_3';
import  AGN_OAM_Local_Name_4 from '@salesforce/label/c.AGN_OAM_Local_Name_4';
import  AGN_OAM_Local_Street from '@salesforce/label/c.AGN_OAM_Local_Street';
import  AGN_OAM_Local_City from '@salesforce/label/c.AGN_OAM_Local_City';
import  AGN_OAM_Local_Search_Term from '@salesforce/label/c.AGN_OAM_Local_Search_Term';
import  AGN_OAM_Tax_Number_3 from '@salesforce/label/c.AGN_OAM_Tax_Number_3';
import  AGN_OAM_Customer_Group_2 from '@salesforce/label/c.AGN_OAM_Customer_Group_2';
import  AGN_OAM_Bank_Account from '@salesforce/label/c.AGN_OAM_Bank_Account';
import  AGN_OAM_Bank_Key from '@salesforce/label/c.AGN_OAM_Bank_Key';
import  AGN_OAM_Control_Key from '@salesforce/label/c.AGN_OAM_Control_Key';
import  AGN_OAM_INN_Number from '@salesforce/label/c.AGN_OAM_INN_Number';
import  AGN_OAM_OKPO_Number from '@salesforce/label/c.AGN_OAM_OKPO_Number';
import  AGN_OAM_KPP_Number from '@salesforce/label/c.AGN_OAM_KPP_Number';
import  AGN_OAM_Contract_Number from '@salesforce/label/c.AGN_OAM_Contract_Number';
import  AGN_OAM_Coiuntry1 from '@salesforce/label/c.AGN_OAM_Coiuntry1';
import  AGN_OAM_Processing_Unit from '@salesforce/label/c.AGN_OAM_Processing_Unit';
import  AGN_OAM_Tax_Classifications from '@salesforce/label/c.AGN_OAM_Tax_Classifications';
import  AGN_OAM_Telephone1 from '@salesforce/label/c.AGN_OAM_Telephone1';
import  AGN_OAM_Tax_Number_AGN from '@salesforce/label/c.AGN_OAM_Tax_Number_AGN';
import  AGN_OAM_Accounting_Office from '@salesforce/label/c.AGN_OAM_Accounting_Office';
import  AGN_OAM_Management_Centre from '@salesforce/label/c.AGN_OAM_Management_Centre';
import  AGN_OAM_Name4 from '@salesforce/label/c.AGN_OAM_Name4';
import  AGN_OAM_Receive_Delivery_Note_with_Price from '@salesforce/label/c.AGN_OAM_Receive_Delivery_Note_with_Price';
import  AGN_OAM_Additional_Shipping_Instructions1 from '@salesforce/label/c.AGN_OAM_Additional_Shipping_Instructions1';
import  AGN_OAM_Customer_Group1 from '@salesforce/label/c.AGN_OAM_Customer_Group1';
import  AGN_OAM_Region_Name from '@salesforce/label/c.AGN_OAM_Region_Name';
import  AGN_OAM_Region_Name1 from '@salesforce/label/c.AGN_OAM_Region_Name1';
import  AGN_OAM_Street2 from '@salesforce/label/c.AGN_OAM_Street2';
import  AGN_OAM_Price_ListS from '@salesforce/label/c.AGN_OAM_Price_ListS';
import  AGN_OAM_Reference_Code from '@salesforce/label/c.AGN_OAM_Reference_Code';
import  AGN_OAM_Accoounting_Clerks from '@salesforce/label/c.AGN_OAM_Accoounting_Clerks';
import  AGN_OAM_Form_Of_Payments from '@salesforce/label/c.AGN_OAM_Form_Of_PaymentS';
import  AGN_OAM_SH_Clinic from '@salesforce/label/c.AGN_OAM_SH_Clinic';
import  AGN_OAM_SH_Private_Address from '@salesforce/label/c.AGN_OAM_SH_Private_Address';
import  AGN_OAM_Not_Home_Address from '@salesforce/label/c.AGN_OAM_Not_Home_Address';
import  AGN_OAM_Sales_Z2 from '@salesforce/label/c.AGN_OAM_Sales_Z2';
import  AGN_OAM_Sales_Z3 from '@salesforce/label/c.AGN_OAM_Sales_Z3';
import  AGN_OAM_Tax_Number_Registered from '@salesforce/label/c.AGN_OAM_Tax_Number_Registered';
import  AGN_OAM_Registration_License_Number_CL_HR_PH_VP from '@salesforce/label/c.AGN_OAM_Registration_License_Number_CL_HR_PH_VP';
import  AGN_OAM_Company_Name_SoldTo_HR_Address from '@salesforce/label/c.AGN_OAM_Company_Name_SoldTo_HR_Address';
import  AGN_OAM_Company_Name_SoldTo_PH_Address from '@salesforce/label/c.AGN_OAM_Company_Name_SoldTo_PH_Address';
import  AGN_OAM_Company_Name_SoldTo_CL_Address from '@salesforce/label/c.AGN_OAM_Company_Name_SoldTo_CL_Address';
import  AGN_OAM_Product_Interest_Es from '@salesforce/label/c.AGN_OAM_Product_Interest_Es';
import  AGN_OAM_Company_Name_4 from '@salesforce/label/c.AGN_OAM_Company_Name_4';
import  AGN_OAM_VAT_Number_CIF from '@salesforce/label/c.AGN_OAM_VAT_Number_CIF';
import  AGN_ICL_CUU_Code_Registerd_Addres from '@salesforce/label/c.AGN_ICL_CUU_Code_Registerd_Addres';
import  AGN_OAM_Tax_Code_Company_Name from '@salesforce/label/c.AGN_OAM_Tax_Code_Company_Name';
import  AGN_OAM_NIF_CIF_Number from '@salesforce/label/c.AGN_OAM_NIF_CIF_Number';
import  AGN_OAM_Product_Interest from '@salesforce/label/c.AGN_OAM_Product_Interest';
import  AGN_OAM_BiillTo_Same_Name_Add from '@salesforce/label/c.AGN_OAM_BiillTo_Same_Name_Add';
import  AGN_OAM_Body_Confirm_Youhave from '@salesforce/label/c.AGN_OAM_Body_Confirm_Youhave';
import  AGN_OAM_Body_Confirm_SuccessfullyCompleted from '@salesforce/label/c.AGN_OAM_Body_Confirm_SuccessfullyCompleted';
import  AGN_OAM_Body_Confirm_CheckInbox from '@salesforce/label/c.AGN_OAM_Body_Confirm_CheckInbox';
import  AGN_OAM_Surcharge_Equivalence from '@salesforce/label/c.AGN_OAM_Surcharge_Equivalence';
import  AGN_OAM_VAT_Number_2 from '@salesforce/label/c.AGN_OAM_VAT_Number_2';
import  AGN_OAM_Company_Name_1 from '@salesforce/label/c.AGN_OAM_Company_Name_1';
import  AGN_OAM_Association_Establishment from '@salesforce/label/c.AGN_OAM_Association_Establishment';
import  AGN_OAM_SAP_Blocking_Status from '@salesforce/label/c.AGN_OAM_SAP_Blocking_Status';
import  AGN_OAM_Name3_PH from '@salesforce/label/c.AGN_OAM_Name3_PH';
import  AGN_OAM_Name3_GP from '@salesforce/label/c.AGN_OAM_Name3_GP';
import  AGN_OAM_Name3_CL from '@salesforce/label/c.AGN_OAM_Name3_CL';
import  AGN_OAM_Name3_HR from '@salesforce/label/c.AGN_OAM_Name3_HR';
import  AGN_OAM_Specialty_Allergan_1 from '@salesforce/label/c.AGN_OAM_Specialty_Allergan_1';
import  AGN_OAM_First_Name_1 from '@salesforce/label/c.AGN_OAM_First_Name_1';
import  AGN_OAM_Last_Name_1 from '@salesforce/label/c.AGN_OAM_Last_Name_1';
import  AGN_OAM_Company_Name_SoldTo_PH_VP_Address from '@salesforce/label/c.AGN_OAM_Company_Name_SoldTo_PH_VP_Address';
import  AGN_OAM_RPPS from '@salesforce/label/c.AGN_OAM_RPPS';
import  AGN_OAM_AAF_Signed from '@salesforce/label/c.AGN_OAM_AAF_Signed';
import  AGN_OAM_VAT_Number_Registered from '@salesforce/label/c.AGN_OAM_VAT_Number_Registered';
import  AGN_OAM_Date_of_Birth from '@salesforce/label/c.AGN_OAM_Date_of_Birth';
import  AGN_OAM_Professional_Designation from '@salesforce/label/c.AGN_OAM_Professional_Designation';
import  AGN_OAM_Nome_Direttore_Sanitario from '@salesforce/label/c.AGN_OAM_Nome_Direttore_Sanitario';
import  AGN_OAM_VAT_Number_4 from '@salesforce/label/c.AGN_OAM_VAT_Number_4';
import  AGN_OAM_Service_code from '@salesforce/label/c.AGN_OAM_Service_code';
import  AGN_OAM_Registration_License_Number_1 from '@salesforce/label/c.AGN_OAM_Registration_License_Number_1';
import  AGN_OAM_Contact_Affiliation from '@salesforce/label/c.AGN_OAM_Contact_Affiliation';
import  AGN_OAM_Product_Interest_SubHeading from '@salesforce/label/c.AGN_OAM_Product_Interest_SubHeading';
import  AGN_OAM_Confirmation_AAF_Date from '@salesforce/label/c.AGN_OAM_Confirmation_AAF_Date';
import  AGN_Consent_to_Email from '@salesforce/label/c.AGN_Consent_to_Email';
import  AGN_Consent_to_Contact from '@salesforce/label/c.AGN_Consent_to_Contact';
import  AGN_Consent_to_Mail from '@salesforce/label/c.AGN_Consent_to_Mail';
import  AGN_OAM_Consent_to_Phone from '@salesforce/label/c.AGN_OAM_Consent_to_Phone';
import  AGN_OAM_Account_Status from '@salesforce/label/c.AGN_OAM_Account_Status';
import  AGN_Sub_Speciality_Allergan from '@salesforce/label/c.AGN_Sub_Speciality_Allergan';
import  AGN_OAM_Graduation_Year from '@salesforce/label/c.AGN_OAM_Graduation_Year';
import  AGN_GCSP_Brick from '@salesforce/label/c.AGN_GCSP_Brick';
import  AGN_Appt_Required from '@salesforce/label/c.AGN_Appt_Required';
import  AGN_Receiptionist_Email from '@salesforce/label/c.AGN_Receiptionist_Email';
import  AGN_Receptionist_Name from '@salesforce/label/c.AGN_Receptionist_Name';
import  AGN_OAM_Phone_2 from '@salesforce/label/c.AGN_OAM_Phone_2';
import  AGN_OAM_Body_Street from '@salesforce/label/c.AGN_OAM_Body_Street';
import  AGN_OAM_Body_Number from '@salesforce/label/c.AGN_OAM_Body_Number';
import  AGN_OAM_Body_Address_Line_2 from '@salesforce/label/c.AGN_OAM_Body_Address_Line_2';
import  AGN_OAM_Body_Address_Line_3 from '@salesforce/label/c.AGN_OAM_Body_Address_Line_3';
import  AGN_OAM_Body_City from '@salesforce/label/c.AGN_OAM_Body_City';
import  AGN_OAM_Body_County from '@salesforce/label/c.AGN_OAM_Body_County';
import  AGN_OAM_Middle_Name from '@salesforce/label/c.AGN_OAM_Middle_Name';
import  AGN_OAM_Body_DOB from '@salesforce/label/c.AGN_OAM_Body_DOB';
import  AGN_OAM_Body_Gender from '@salesforce/label/c.AGN_OAM_Body_Gender';
import  AGN_OAM_Body_PurposeOfBusiness from '@salesforce/label/c.AGN_OAM_Body_PurposeOfBusiness';
import  AGN_OAM_Body_Preferred from '@salesforce/label/c.AGN_OAM_Body_Preferred';
import  AGN_Physician_Registration_Reference from '@salesforce/label/c.AGN_Physician_Registration_Reference';
import  AGN_OAM_Body_Mobile from '@salesforce/label/c.AGN_OAM_Body_Mobile';
import  AGN_OAM_Body_Phone from '@salesforce/label/c.AGN_OAM_Body_Phone';
import  AGN_OAM_Body_Email from '@salesforce/label/c.AGN_OAM_Body_Email';
import  AGN_OAM_Body_Email2 from '@salesforce/label/c.AGN_OAM_Body_Email2';
import  AGN_OAM_State_Registration from '@salesforce/label/c.AGN_OAM_State_Registration';
import  AGN_OAM_CPF_CNPJ from '@salesforce/label/c.AGN_OAM_CPF_CNPJ';
import  AGN_OAM_CRM_CRO from '@salesforce/label/c.AGN_OAM_CRM_CRO';
import  AGN_OAM_CRM_CRO_UF from '@salesforce/label/c.AGN_OAM_CRM_CRO_UF';
import  AGN_OAM_Body_Name from '@salesforce/label/c.AGN_OAM_Body_Name';
import  AGN_OAM_Body_Surname from '@salesforce/label/c.AGN_OAM_Body_Surname';
import  AGN_OAM_Body_Title from '@salesforce/label/c.AGN_OAM_Body_Title';
import  AGN_OAM_Body_PostalCode from '@salesforce/label/c.AGN_OAM_Body_PostalCode';
import  AGN_OAM_Body_BusinessPracticeName from '@salesforce/label/c.AGN_OAM_Body_BusinessPracticeName';
import  AGN_OAM_Body_DepartmentName from '@salesforce/label/c.AGN_OAM_Body_DepartmentName';
import  AGN_OAM_Body_Address from '@salesforce/label/c.AGN_OAM_Body_Address';
import  AGN_OAM_Communication_Contact from '@salesforce/label/c.AGN_OAM_Communication_Contact';
import  AGN_OAM_Address from '@salesforce/label/c.AGN_OAM_Address';
import  AGN_OAM_Business_Unit from '@salesforce/label/c.AGN_OAM_Business_Unit';
import  AGN_OAM_Street_Name from '@salesforce/label/c.AGN_OAM_Street_Name';
import  AGN_OAM_House_Number from '@salesforce/label/c.AGN_OAM_House_Number';
import  AGN_OAM_Body_State from '@salesforce/label/c.AGN_OAM_Body_State';
import  AGN_OAM_BussinessEmail from '@salesforce/label/c.AGN_OAM_BussinessEmail';
import  AGN_OAM_Surname from '@salesforce/label/c.AGN_OAM_Surname';
import  AGN_OAM_Address_Line_2 from '@salesforce/label/c.AGN_OAM_Address_Line_2';
import  AGN_OAM_Postal_Code from '@salesforce/label/c.AGN_OAM_Postal_Code';
import  AGN_OAM_Suburb from '@salesforce/label/c.AGN_OAM_Suburb';
import  AGN_OAM_Product_Interest_ANZ from '@salesforce/label/c.AGN_OAM_Product_Interest_ANZ';
import  AGN_OAM_Additional_Phone from '@salesforce/label/c.AGN_OAM_Additional_Phone';
import  AGN_OAM_Prescribing_doctor_Account from '@salesforce/label/c.AGN_OAM_Prescribing_doctor_Account';
import  AGN_OAM_NZBN_Number from '@salesforce/label/c.AGN_OAM_NZBN_Number';
import  AGN_OAM_Comments from '@salesforce/label/c.AGN_OAM_Comments';
import  AGN_OAM_Name from '@salesforce/label/c.AGN_OAM_Name';
import  AGN_OAM_Street_Number from '@salesforce/label/c.AGN_OAM_Street_Number';
import  AGN_OAM_Company_Number from '@salesforce/label/c.AGN_OAM_Company_Number';
import  AGN_OAM_Bussiness_Name from '@salesforce/label/c.AGN_OAM_Bussiness_Name';
import  AGN_OAM_Account_Changes from '@salesforce/label/c.AGN_OAM_Account_Changes';
import  AGN_OAM_Portal_Department_Name from '@salesforce/label/c.AGN_OAM_Portal_Department_Name';
import  AGN_OAM_Bussiness_Name_ShipTo from '@salesforce/label/c.AGN_OAM_Bussiness_Name_ShipTo';
import  AGN_OAM_Bussiness_Name_BillTo from '@salesforce/label/c.AGN_OAM_Bussiness_Name_BillTo';
import  AGN_OAM_Prescribing_Dr_Registration_Number from '@salesforce/label/c.AGN_OAM_Prescribing_Dr_Registration_Number';
import  AGN_OAM_Prescribing_Dr_HPI_Number from '@salesforce/label/c.AGN_OAM_Prescribing_Dr_HPI_Number';
import  AGN_OAM_Business_Name_Reference1 from '@salesforce/label/c.AGN_OAM_Business_Name_Reference1';
import  AGN_OAM_Contact_Name_Reference1 from '@salesforce/label/c.AGN_OAM_Contact_Name_Reference1';
import  AGN_OAM_Phone_Reference1 from '@salesforce/label/c.AGN_OAM_Phone_Reference1';
import  AGN_OAM_Email_Reference1 from '@salesforce/label/c.AGN_OAM_Email_Reference1';
import  AGN_OAM_Overseeing_accountID from '@salesforce/label/c.AGN_OAM_Overseeing_accountID';
import  AGN_OAM_Suite from '@salesforce/label/c.AGN_OAM_Suite';
import  AGN_OAM_Registred_Home_Address from '@salesforce/label/c.AGN_OAM_Registred_Home_Address';
import  AGN_OAM_ACCOUNT_OWNER_EMAIL from '@salesforce/label/c.AGN_OAM_ACCOUNT_OWNER_EMAIL';
import  AGN_OAM_CONSENT_TO_ALBERTA from '@salesforce/label/c.AGN_OAM_CONSENT_TO_ALBERTA';
import  AGN_OAM_Physician_License_Number from '@salesforce/label/c.AGN_OAM_Physician_License_Number';
import  AGN_OAM_Bussiness_Registration_Number from '@salesforce/label/c.AGN_OAM_Bussiness_Registration_Number';
import  AGN_OAM_Business_Name_Reference2 from '@salesforce/label/c.AGN_OAM_Business_Name_Reference2';
import  AGN_OAM_Contact_Name_Reference2 from '@salesforce/label/c.AGN_OAM_Contact_Name_Reference2';
import  AGN_OAM_Fax_Reference2 from '@salesforce/label/c.AGN_OAM_Fax_Reference2';
import  AGN_OAM_Fax_Reference1 from '@salesforce/label/c.AGN_OAM_Fax_Reference1';
import  AGN_OAM_Phone_Reference2 from '@salesforce/label/c.AGN_OAM_Phone_Reference2';
import  AGN_OAM_Hospital_Name from '@salesforce/label/c.AGN_OAM_Hospital_Name';
import  AGN_OAM_Hospital_Phone from '@salesforce/label/c.AGN_OAM_Hospital_Phone';
import  AGN_OAM_Doctors_Name from '@salesforce/label/c.AGN_OAM_Doctors_Name';
import  AGN_OAM_Primary_Pharmacist_Email from '@salesforce/label/c.AGN_OAM_Primary_Pharmacist_Email';
import  AGN_OAM_Primary_Physician_Phone from '@salesforce/label/c.AGN_OAM_Primary_Physician_Phone';
import  AGN_OAM_Primary_Physician_Email from '@salesforce/label/c.AGN_OAM_Primary_Physician_Email';
import  AGN_OAM_Primary_Pharmacist_Name from '@salesforce/label/c.AGN_OAM_Primary_Pharmacist_Name';
import  AGN_OAM_VERIFIED_ADDRESS from '@salesforce/label/c.AGN_OAM_VERIFIED_ADDRESS';
import  AGN_OAM_Doctors_SurName from '@salesforce/label/c.AGN_OAM_Doctors_SurName';
import  AGN_OAM_License_Number from '@salesforce/label/c.AGN_OAM_License_Number';
import  AGN_OAM_Primary_Physician_Name from '@salesforce/label/c.AGN_OAM_Primary_Physician_Name';
import  AGN_OAM_Pharmacy_license_number from '@salesforce/label/c.AGN_OAM_Pharmacy_license_number';
import  AGN_OAM_Primary_Pharmacist_Phone from '@salesforce/label/c.AGN_OAM_Primary_Pharmacist_Phone';
import  AGN_OAM_Hospital_Email from '@salesforce/label/c.AGN_OAM_Hospital_Email';
import  AGN_OAM_Business_Name_Reference3 from '@salesforce/label/c.AGN_OAM_Business_Name_Reference3';
import  AGN_OAM_Email_Reference2 from '@salesforce/label/c.AGN_OAM_Email_Reference2';
import  AGN_OAM_Contact_Name_Reference3 from '@salesforce/label/c.AGN_OAM_Contact_Name_Reference3';
import  AGN_OAM_Phone_Reference3 from '@salesforce/label/c.AGN_OAM_Phone_Reference3';
import  AGN_OAM_Email_Reference3 from '@salesforce/label/c.AGN_OAM_Email_Reference3';
import  AGN_OAM_Consignment_Authorized from '@salesforce/label/c.AGN_OAM_Consignment_Authorized';
import  AGN_OAM_First_Name_CS from '@salesforce/label/c.AGN_OAM_First_Name_CS';
import  AGN_OAM_Last_Name_CS from '@salesforce/label/c.AGN_OAM_Last_Name_CS';
import  AGN_OAM_Email_CS from '@salesforce/label/c.AGN_OAM_Email_CS';
import  AGN_OAM_Province_CS from '@salesforce/label/c.AGN_OAM_Province_CS';
import  AGN_OAM_Salutation_CS from '@salesforce/label/c.AGN_OAM_Salutation_CS';
import  AGN_OAM_Phone_CS from '@salesforce/label/c.AGN_OAM_Phone_CS';
import  AGN_OAM_Name_1 from '@salesforce/label/c.AGN_OAM_Name_1';
import  AGN_OAM_Name_2 from '@salesforce/label/c.AGN_OAM_Name_2';
import  AGN_OAM_State2 from '@salesforce/label/c.AGN_OAM_State2';
import  AGN_OAM_Company_Name_Medecian_DN from '@salesforce/label/c.AGN_OAM_Company_Name_Medecian_DN';
import  AGN_GCSP_RegistrationLicense_No from '@salesforce/label/c.AGN_GCSP_RegistrationLicense_No';
import  AGN_Article_23_Text_2 from '@salesforce/label/c.AGN_Article_23_Text_2';
import  AGN_OAM_NameHeadIsPharmasist from '@salesforce/label/c.AGN_OAM_NameHeadIsPharmasist';
import  AGN_OAM_Company_Name_1_Bill_To_CL from '@salesforce/label/c.AGN_OAM_Company_Name_1_Bill_To_CL';
import  AGN_OAM_Big_Number from '@salesforce/label/c.AGN_OAM_Big_Number';
import  AGN_OAM_VAT_Reg_No from '@salesforce/label/c.AGN_OAM_VAT_Reg_No';
import  AGN_OAM_Wholesaler_Distributor_Licence from '@salesforce/label/c.AGN_OAM_Wholesaler_Distributor_Licence';
import  AGN_OAM_Reference_1 from '@salesforce/label/c.AGN_OAM_Reference_1';
import  AGN_OAM_Reference_2 from '@salesforce/label/c.AGN_OAM_Reference_2';
import  AGN_OAM_Reference_3 from '@salesforce/label/c.AGN_OAM_Reference_3';
import  AGN_OAM_ABN_Number from '@salesforce/label/c.AGN_OAM_ABN_Number';
import  AGN_OAM_Prescribing_Doc_First_Name from '@salesforce/label/c.AGN_OAM_Prescribing_Doc_First_Name';
import  AGN_OAM_Prescribing_Doc_Middle_Name from '@salesforce/label/c.AGN_OAM_Prescribing_Doc_Middle_Name';
import  AGN_OAM_Prescribing_Doc_Last_Name from '@salesforce/label/c.AGN_OAM_Prescribing_Doc_Last_Name';
import  AGN_OAM_Prescribing_Doc_Email from '@salesforce/label/c.AGN_OAM_Prescribing_Doc_Email';
import  AGN_OAM_Prescribing_Doc_Phone from '@salesforce/label/c.AGN_OAM_Prescribing_Doc_Phone';
import  AGN_OAM_Prescribing_Dr_AHPRA_Registration_Number from '@salesforce/label/c.AGN_OAM_Prescribing_Dr_AHPRA_Registration_Number';
import  AGN_OAM_Nurse_Practitioners_AHPRA_Registration_Number from '@salesforce/label/c.AGN_OAM_Nurse_Practitioners_AHPRA_Registration_Number';
import  AGN_OAM_Nurse_Practitioners_Registration_Number from '@salesforce/label/c.AGN_OAM_Nurse_Practitioners_Registration_Number';
import  AGN_OAM_Nurse_Practitioners_HPI_Number from '@salesforce/label/c.AGN_OAM_Nurse_Practitioners_HPI_Number';
// added by Kunal and Sachin:  For Canada Help text:
import  AGN_OAM_Help_Text_Is_this_a_registred_home_address from '@salesforce/label/c.AGN_OAM_Help_Text_Is_this_a_registred_home_address';
import  AGN_OAM_Help_Text_Overseeing_ID from '@salesforce/label/c.AGN_OAM_Help_Text_Overseeing_ID';
import  AGN_Account_Authority_Help_Text from '@salesforce/label/c.AGN_Account_Authority_Help_Text';
import  AGN_License_Number_Help_Text from '@salesforce/label/c.AGN_License_Number_Help_Text';
import  AGN_Overseeing_Acc_No_Help from '@salesforce/label/c.AGN_Overseeing_Acc_No_Help';
import  AGN_Physician_license_help_text from '@salesforce/label/c.AGN_Physician_license_help_text';
import  AGN_Customer_behalf_owner_help from '@salesforce/label/c.AGN_Customer_behalf_owner_help';
import  AGN_License_Number_CS_Help_Text from '@salesforce/label/c.AGN_License_Number_CS_Help_Text';
//end
import AGN_OAM_Are_you_the_account_authority from '@salesforce/label/c.AGN_OAM_Are_you_the_account_authority';
import AGN_OAM_information_for_communication from '@salesforce/label/c.AGN_OAM_information_for_communication';
import AGN_OAM_Shipping_Instructions from '@salesforce/label/c.AGN_OAM_Shipping_Instructions';
import AGN_OAM_Doctors_First_Name from '@salesforce/label/c.AGN_OAM_Doctors_First_Name';
import AGN_OAM_ACCOUNT_OWNER_EMAIL_FIELD from '@salesforce/label/c.AGN_OAM_ACCOUNT_OWNER_EMAIL_FIELD';
import AGN_OAM_ACCOUNT_OWNER_FIRSTNAME from '@salesforce/label/c.AGN_OAM_ACCOUNT_OWNER_FIRSTNAME';
import AGN_OAM_ACCOUNT_OWNER_LASTNAMES from '@salesforce/label/c.AGN_OAM_ACCOUNT_OWNER_LASTNAMES';
import AGN_OAM_Doctors_Last_Name from '@salesforce/label/c.AGN_OAM_Doctors_Last_Name';
import AGN_OAM_Doctor_Overseeing_Account_in_Allergan from '@salesforce/label/c.AGN_OAM_Doctor_Overseeing_Account_in_Allergan';
import AGN_OAM_DEA_Number from '@salesforce/label/c.AGN_OAM_DEA_Number';
import AGN_OAM_Doctors_Email from '@salesforce/label/c.AGN_OAM_Doctors_Email';
import AGN_OAM_License_Number_US from '@salesforce/label/c.AGN_OAM_License_Number_US';
import AGN_OAM_US_State_Name from '@salesforce/label/c.AGN_OAM_US_State_Name';
import AGN_OAM_US_State from '@salesforce/label/c.AGN_OAM_US_State';
import AGN_OAM_US_License_HCP from '@salesforce/label/c.AGN_OAM_US_License_HCP';
import AGN_OAM_SAP_Name_1 from '@salesforce/label/c.AGN_OAM_SAP_Name_1';
import AGN_OAM_SAP_Name_2 from '@salesforce/label/c.AGN_OAM_SAP_Name_2';
import AGN_OAM_Default_AGN from '@salesforce/label/c.AGN_OAM_Default_AGN';
import AGN_OAM_Suite2 from '@salesforce/label/c.AGN_OAM_Suite2';
import AGN_OAM_Title_1 from '@salesforce/label/c.AGN_OAM_Title_1';
import AGN_OAM_Body_Agree from '@salesforce/label/c.AGN_OAM_Body_Agree';
import AGN_OAM_Body_TermsConditions from '@salesforce/label/c.AGN_OAM_Body_TermsConditions';
import AGN_OAM_Body_Ok from '@salesforce/label/c.AGN_OAM_Body_Ok';
import AGN_OAM_Body_Cancel from '@salesforce/label/c.AGN_OAM_Body_Cancel';
import AGN_OAM_Gender_CS from '@salesforce/label/c.AGN_OAM_Gender_CS';
import AGN_OAM_Mobile_CS from '@salesforce/label/c.AGN_OAM_Mobile_CS';
import AGN_OAM_US_License_Holder from '@salesforce/label/c.AGN_OAM_US_License_Holder';
import AGN_OAM_Part_of_a_Buying_Group from '@salesforce/label/c.AGN_OAM_Part_of_a_Buying_Group';

import AGN_OAM_Member_Account_Number from '@salesforce/label/c.AGN_OAM_Member_Account_Number';
import AGN_OAM_Are_you_apart_Buying_Group from '@salesforce/label/c.AGN_OAM_Are_you_apart_Buying_Group';
import AGN_OAM_Buying_Group_Name from '@salesforce/label/c.AGN_OAM_Buying_Group_Name';
import AGN_OAM_Electronic_Invoice from '@salesforce/label/c.AGN_OAM_Electronic_Invoice';

const getCustomLable = () => {
    var labelMap = new Map();
	//added for canada help text:
	labelMap.set('AGN_OAM_Help_Text_Is_this_a_registred_home_address',  AGN_OAM_Help_Text_Is_this_a_registred_home_address);
	labelMap.set('AGN_OAM_Help_Text_Overseeing_ID',  AGN_OAM_Help_Text_Overseeing_ID);
	labelMap.set('AGN_Account_Authority_Help_Text',  AGN_Account_Authority_Help_Text);
	labelMap.set('AGN_License_Number_Help_Text',  AGN_License_Number_Help_Text);
	labelMap.set('AGN_Overseeing_Acc_No_Help',  AGN_Overseeing_Acc_No_Help);
	labelMap.set('AGN_Physician_license_help_text',  AGN_Physician_license_help_text);
	labelMap.set('AGN_Customer_behalf_owner_help',  AGN_Customer_behalf_owner_help);
	labelMap.set('AGN_License_Number_CS_Help_Text',  AGN_License_Number_CS_Help_Text);
	//end
	//
	labelMap.set('AGN_OAM_Are_you_the_account_authority', AGN_OAM_Are_you_the_account_authority);
    labelMap.set('AGN_OAM_information_for_communication', AGN_OAM_information_for_communication);
    labelMap.set('AGN_OAM_Shipping_Instructions', AGN_OAM_Shipping_Instructions);
    labelMap.set('AGN_OAM_Doctors_First_Name', AGN_OAM_Doctors_First_Name);
    //labelMap.set('AGN_OAM_Street_Number', AGN_OAM_Street_Number);
    labelMap.set('AGN_OAM_ACCOUNT_OWNER_EMAIL_FIELD', AGN_OAM_ACCOUNT_OWNER_EMAIL_FIELD);
    labelMap.set('AGN_OAM_ACCOUNT_OWNER_FIRSTNAME', AGN_OAM_ACCOUNT_OWNER_FIRSTNAME);
    labelMap.set('AGN_OAM_ACCOUNT_OWNER_LASTNAMES', AGN_OAM_ACCOUNT_OWNER_LASTNAMES);
	labelMap.set('AGN_OAM_Doctors_Last_Name', AGN_OAM_Doctors_Last_Name);
	labelMap.set('AGN_OAM_Title_1', AGN_OAM_Title_1);
	 
	labelMap.set('AGN_OAM_Doctor_Overseeing_Account_in_Allergan', AGN_OAM_Doctor_Overseeing_Account_in_Allergan);
    labelMap.set('AGN_OAM_Member_Account_Number', AGN_OAM_Member_Account_Number);
    labelMap.set('AGN_OAM_US_State', AGN_OAM_US_State);
    labelMap.set('AGN_OAM_DEA_Number', AGN_OAM_DEA_Number);
    labelMap.set('AGN_OAM_Doctors_Email', AGN_OAM_Doctors_Email);
    labelMap.set('AGN_OAM_License_Number_US', AGN_OAM_License_Number_US);
    labelMap.set('AGN_OAM_US_State_Name', AGN_OAM_US_State_Name);
    labelMap.set('AGN_OAM_US_License_HCP', AGN_OAM_US_License_HCP);
    labelMap.set('AGN_OAM_SAP_Name_1', AGN_OAM_SAP_Name_1);
    labelMap.set('AGN_OAM_SAP_Name_2', AGN_OAM_SAP_Name_2);
    labelMap.set('AGN_OAM_Default_AGN', AGN_OAM_Default_AGN);
    labelMap.set('AGN_OAM_Suite2', AGN_OAM_Suite2);
	labelMap.set('AGN_OAM_Body_Agree', AGN_OAM_Body_Agree);
	labelMap.set('AGN_OAM_Body_TermsConditions', AGN_OAM_Body_TermsConditions);
	
	labelMap.set('AGN_OAM_Body_Ok', AGN_OAM_Body_Ok);
    labelMap.set('AGN_OAM_Body_Cancel', AGN_OAM_Body_Cancel);
	labelMap.set('AGN_OAM_Gender_CS', AGN_OAM_Gender_CS);
	labelMap.set('AGN_OAM_Mobile_CS', AGN_OAM_Mobile_CS);
	labelMap.set('AGN_OAM_US_License_Holder', AGN_OAM_US_License_Holder);
	labelMap.set('AGN_OAM_Part_of_a_Buying_Group', AGN_OAM_Part_of_a_Buying_Group);
	//
	labelMap.set('AGN_OAM_Electronic_Invoice', AGN_OAM_Electronic_Invoice);
    labelMap.set('AGN_OAM_Are_you_apart_Buying_Group', AGN_OAM_Are_you_apart_Buying_Group);
    labelMap.set('AGN_OAM_Buying_Group_Name', AGN_OAM_Buying_Group_Name);
    labelMap.set('AGN_OAM_Website_Link',  AGN_OAM_Website_Link);
	labelMap.set('AGN_OAM_Mapping_2',  AGN_OAM_Mapping_2);
	labelMap.set('AGN_OAM_Mapping_1',  AGN_OAM_Mapping_1);
	labelMap.set('AGN_OAM_Distribution_ID',  AGN_OAM_Distribution_ID);
	labelMap.set('AGN_OAM_Additional_Comments',  AGN_OAM_Additional_Comments);
	labelMap.set('AGN_OAM_Company_Name_3',  AGN_OAM_Company_Name_3);
	labelMap.set('AGN_OAM_Company_Name_2',  AGN_OAM_Company_Name_2);
	labelMap.set('AGN_OAM_Address_Line_1',  AGN_OAM_Address_Line_1);
	labelMap.set('AGN_OAM_Address_Line_1_1',  AGN_OAM_Address_Line_1_1);
	labelMap.set('AGN_OAM_Bank_Account_Number',  AGN_OAM_Bank_Account_Number);
	labelMap.set('AGN_OAM_BanK_Name',  AGN_OAM_BanK_Name);
	labelMap.set('AGN_OAM_City',  AGN_OAM_City);
	labelMap.set('AGN_OAM_Company_Name',  AGN_OAM_Company_Name);
	labelMap.set('AGN_OAM_Body_Country',  AGN_OAM_Body_Country);
	labelMap.set('AGN_OAM_Department_Name',  AGN_OAM_Department_Name);
	labelMap.set('AGN_OAM_Email_1',  AGN_OAM_Email_1);
	labelMap.set('AGN_OAM_Email',  AGN_OAM_Email);
	labelMap.set('AGN_OAM_First_Name',  AGN_OAM_First_Name);
	labelMap.set('AGN_OAM_IBAN',  AGN_OAM_IBAN);
	labelMap.set('AGN_OAM_Last_Name',  AGN_OAM_Last_Name);
	labelMap.set('AGN_OAM_Phone',  AGN_OAM_Phone);
	labelMap.set('AGN_OAM_Preferred_Communication',  AGN_OAM_Preferred_Communication);
	labelMap.set('AGN_OAM_Registration_License_Number',  AGN_OAM_Registration_License_Number);
	labelMap.set('AGN_OAM_Salutation',  AGN_OAM_Salutation);
	labelMap.set('AGN_OAM_Sort_Code',  AGN_OAM_Sort_Code);
	labelMap.set('AGN_OAM_State',  AGN_OAM_State);
	labelMap.set('AGN_OAM_SWIFT_BIC',  AGN_OAM_SWIFT_BIC);
	labelMap.set('AGN_OAM_Tax_Exempted',  AGN_OAM_Tax_Exempted);
	labelMap.set('AGN_OAM_Tax_Number',  AGN_OAM_Tax_Number);
	labelMap.set('AGN_OAM_Tax_Number_1',  AGN_OAM_Tax_Number_1);
	labelMap.set('AGN_OAM_VAT_Number',  AGN_OAM_VAT_Number);
	labelMap.set('AGN_OAM_ZIP_Code',  AGN_OAM_ZIP_Code);
	labelMap.set('AGN_OAM_Additional_Shipping_Ins',  AGN_OAM_Additional_Shipping_Ins);
	labelMap.set('AGN_OAM_Customer_Group',  AGN_OAM_Customer_Group);
	labelMap.set('AGN_OAM_Contact_Person_Type',  AGN_OAM_Contact_Person_Type);
	labelMap.set('AGN_OAM_Gender',  AGN_OAM_Gender);
	labelMap.set('AGN_OAM_Language',  AGN_OAM_Language);
	labelMap.set('AGN_OAM_Enable_OAM_Portal_Access',  AGN_OAM_Enable_OAM_Portal_Access);
	labelMap.set('AGN_OAM_Name1',  AGN_OAM_Name1);
	labelMap.set('AGN_OAM_Name2',  AGN_OAM_Name2);
	labelMap.set('AGN_OAM_Name3',  AGN_OAM_Name3);
	labelMap.set('AGN_OAM_SAP_Name_4',  AGN_OAM_SAP_Name_4);
	labelMap.set('AGN_OAM_Shipping_Instruction',  AGN_OAM_Shipping_Instruction);
	labelMap.set('AGN_OAM_Sales_Text_1',  AGN_OAM_Sales_Text_1);
	labelMap.set('AGN_OAM_Article_23_relevant',  AGN_OAM_Article_23_relevant);
	labelMap.set('AGN_OAM_Shipping_Instructions_AGN_c',  AGN_OAM_Shipping_Instructions_AGN_c);
	labelMap.set('AGN_OAM_SAP_SalesText_AGN_c',  AGN_OAM_SAP_SalesText_AGN_c);
	labelMap.set('AGN_OAM_First_Name_AGN',  AGN_OAM_First_Name_AGN);
	labelMap.set('AGN_OAM_Last_Name_2',  AGN_OAM_Last_Name_2);
	labelMap.set('AGN_OAM_Phone_AGN',  AGN_OAM_Phone_AGN);
	labelMap.set('AGN_OAM_Shipping_Address',  AGN_OAM_Shipping_Address);
	labelMap.set('AGN_OAM_Billing_Address',  AGN_OAM_Billing_Address);
	labelMap.set('AGN_OAM_Registered_Address',  AGN_OAM_Registered_Address);
	labelMap.set('AGN_OAM_Basic_Information',  AGN_OAM_Basic_Information);
	labelMap.set('AGN_OAM_Fax',  AGN_OAM_Fax);
	labelMap.set('AGN_OAM_SED_SLI_Instructions',  AGN_OAM_SED_SLI_Instructions);
	labelMap.set('AGN_OAM_Public_Private',  AGN_OAM_Public_Private);
	labelMap.set('AGN_OAM_Default_Ship_To',  AGN_OAM_Default_Ship_To);
	labelMap.set('AGN_OAM_Default_Bill_To',  AGN_OAM_Default_Bill_To);
	labelMap.set('AGN_OAM_Body_PaymentMethod',  AGN_OAM_Body_PaymentMethod);
	labelMap.set('AGN_OAM_Tax_Classification',  AGN_OAM_Tax_Classification);
	labelMap.set('AGN_OAM_Price_Group',  AGN_OAM_Price_Group);
	labelMap.set('AGN_OAM_Price_List',  AGN_OAM_Price_List);
	labelMap.set('AGN_OAM_VAT',  AGN_OAM_VAT);
	labelMap.set('AGN_OAM_VAT_Number_1',  AGN_OAM_VAT_Number_1);
	labelMap.set('AGN_OAM_CIP_Number',  AGN_OAM_CIP_Number);
	labelMap.set('AGN_OAM_MOH_Number',  AGN_OAM_MOH_Number);
	labelMap.set('AGN_OAM_Province',  AGN_OAM_Province);
	labelMap.set('AGN_OAM_Payment_Term',  AGN_OAM_Payment_Term);
	labelMap.set('AGN_OAM_CUU_Code',  AGN_OAM_CUU_Code);
	labelMap.set('AGN_OAM_VAT_Number_CL_HR_PH_VP',  AGN_OAM_VAT_Number_CL_HR_PH_VP);
	labelMap.set('AGN_OAM_Codice_Fiscal',  AGN_OAM_Codice_Fiscal);
	labelMap.set('AGN_OAM_Region',  AGN_OAM_Region);
	labelMap.set('AGN_OAM_VAT_Number_3',  AGN_OAM_VAT_Number_3);
	labelMap.set('AGN_OAM_Tax_Office',  AGN_OAM_Tax_Office);
	labelMap.set('AGN_OAM_Sales_District',  AGN_OAM_Sales_District);
	labelMap.set('AGN_OAM_Phone_1',  AGN_OAM_Phone_1);
	labelMap.set('AGN_OAM_District',  AGN_OAM_District);
	labelMap.set('AGN_OAM_State_License_Number',  AGN_OAM_State_License_Number);
	labelMap.set('AGN_OAM_Local_Title',  AGN_OAM_Local_Title);
	labelMap.set('AGN_OAM_Local_Name',  AGN_OAM_Local_Name);
	labelMap.set('AGN_OAM_Local_Name_2',  AGN_OAM_Local_Name_2);
	labelMap.set('AGN_OAM_Local_Name_3',  AGN_OAM_Local_Name_3);
	labelMap.set('AGN_OAM_Local_Name_4',  AGN_OAM_Local_Name_4);
	labelMap.set('AGN_OAM_Local_Street',  AGN_OAM_Local_Street);
	labelMap.set('AGN_OAM_Local_City',  AGN_OAM_Local_City);
	labelMap.set('AGN_OAM_Local_Search_Term',  AGN_OAM_Local_Search_Term);
	labelMap.set('AGN_OAM_Tax_Number_3',  AGN_OAM_Tax_Number_3);
	labelMap.set('AGN_OAM_Customer_Group_2',  AGN_OAM_Customer_Group_2);
	labelMap.set('AGN_OAM_Bank_Account',  AGN_OAM_Bank_Account);
	labelMap.set('AGN_OAM_Bank_Key',  AGN_OAM_Bank_Key);
	labelMap.set('AGN_OAM_Control_Key',  AGN_OAM_Control_Key);
	labelMap.set('AGN_OAM_INN_Number',  AGN_OAM_INN_Number);
	labelMap.set('AGN_OAM_OKPO_Number',  AGN_OAM_OKPO_Number);
	labelMap.set('AGN_OAM_KPP_Number',  AGN_OAM_KPP_Number);
	labelMap.set('AGN_OAM_Contract_Number',  AGN_OAM_Contract_Number);
	labelMap.set('AGN_OAM_Coiuntry1',  AGN_OAM_Coiuntry1);
	labelMap.set('AGN_OAM_Processing_Unit',  AGN_OAM_Processing_Unit);
	labelMap.set('AGN_OAM_Tax_Classifications',  AGN_OAM_Tax_Classifications);
	labelMap.set('AGN_OAM_Telephone1',  AGN_OAM_Telephone1);
	labelMap.set('AGN_OAM_Tax_Number_AGN',  AGN_OAM_Tax_Number_AGN);
	labelMap.set('AGN_OAM_Accounting_Office',  AGN_OAM_Accounting_Office);
	labelMap.set('AGN_OAM_Management_Centre',  AGN_OAM_Management_Centre);
	labelMap.set('AGN_OAM_Name4',  AGN_OAM_Name4);
	labelMap.set('AGN_OAM_Receive_Delivery_Note_with_Price',  AGN_OAM_Receive_Delivery_Note_with_Price);
	labelMap.set('AGN_OAM_Additional_Shipping_Instructions1',  AGN_OAM_Additional_Shipping_Instructions1);
	labelMap.set('AGN_OAM_Customer_Group1',  AGN_OAM_Customer_Group1);
	labelMap.set('AGN_OAM_Region_Name',  AGN_OAM_Region_Name);
	labelMap.set('AGN_OAM_Region_Name1',  AGN_OAM_Region_Name1);
	labelMap.set('AGN_OAM_Street2',  AGN_OAM_Street2);
	labelMap.set('AGN_OAM_Price_ListS',  AGN_OAM_Price_ListS);
	labelMap.set('AGN_OAM_Reference_Code',  AGN_OAM_Reference_Code);
	labelMap.set('AGN_OAM_Accoounting_Clerks',  AGN_OAM_Accoounting_Clerks);
	labelMap.set('AGN_OAM_Form_Of_Payments',  AGN_OAM_Form_Of_Payments);
	labelMap.set('AGN_OAM_SH_Clinic',  AGN_OAM_SH_Clinic);
	labelMap.set('AGN_OAM_SH_Private_Address',  AGN_OAM_SH_Private_Address);
	labelMap.set('AGN_OAM_Not_Home_Address',  AGN_OAM_Not_Home_Address);
	labelMap.set('AGN_OAM_Sales_Z2',  AGN_OAM_Sales_Z2);
	labelMap.set('AGN_OAM_Sales_Z3',  AGN_OAM_Sales_Z3);
	labelMap.set('AGN_OAM_Tax_Number_Registered',  AGN_OAM_Tax_Number_Registered);
	labelMap.set('AGN_OAM_Registration_License_Number_CL_HR_PH_VP',  AGN_OAM_Registration_License_Number_CL_HR_PH_VP);
	labelMap.set('AGN_OAM_Company_Name_SoldTo_HR_Address',  AGN_OAM_Company_Name_SoldTo_HR_Address);
	labelMap.set('AGN_OAM_Company_Name_SoldTo_PH_Address',  AGN_OAM_Company_Name_SoldTo_PH_Address);
	labelMap.set('AGN_OAM_Company_Name_SoldTo_CL_Address',  AGN_OAM_Company_Name_SoldTo_CL_Address);
	labelMap.set('AGN_OAM_Product_Interest_Es',  AGN_OAM_Product_Interest_Es);
	labelMap.set('AGN_OAM_Company_Name_4',  AGN_OAM_Company_Name_4);
	labelMap.set('AGN_OAM_VAT_Number_CIF',  AGN_OAM_VAT_Number_CIF);
	labelMap.set('AGN_ICL_CUU_Code_Registerd_Addres',  AGN_ICL_CUU_Code_Registerd_Addres);
	labelMap.set('AGN_OAM_Tax_Code_Company_Name',  AGN_OAM_Tax_Code_Company_Name);
	labelMap.set('AGN_OAM_NIF_CIF_Number',  AGN_OAM_NIF_CIF_Number);
	labelMap.set('AGN_OAM_Product_Interest',  AGN_OAM_Product_Interest);
	labelMap.set('AGN_OAM_BiillTo_Same_Name_Add',  AGN_OAM_BiillTo_Same_Name_Add);
	labelMap.set('AGN_OAM_Body_Confirm_Youhave',  AGN_OAM_Body_Confirm_Youhave);
	labelMap.set('AGN_OAM_Body_Confirm_SuccessfullyCompleted',  AGN_OAM_Body_Confirm_SuccessfullyCompleted);
	labelMap.set('AGN_OAM_Body_Confirm_CheckInbox',  AGN_OAM_Body_Confirm_CheckInbox);
	labelMap.set('AGN_OAM_Surcharge_Equivalence',  AGN_OAM_Surcharge_Equivalence);
	labelMap.set('AGN_OAM_VAT_Number_2',  AGN_OAM_VAT_Number_2);
	labelMap.set('AGN_OAM_Company_Name_1',  AGN_OAM_Company_Name_1);
	labelMap.set('AGN_OAM_Association_Establishment',  AGN_OAM_Association_Establishment);
	labelMap.set('AGN_OAM_SAP_Blocking_Status',  AGN_OAM_SAP_Blocking_Status);
	labelMap.set('AGN_OAM_Name3_PH',  AGN_OAM_Name3_PH);
	labelMap.set('AGN_OAM_Name3_GP',  AGN_OAM_Name3_GP);
	labelMap.set('AGN_OAM_Name3_CL',  AGN_OAM_Name3_CL);
	labelMap.set('AGN_OAM_Name3_HR',  AGN_OAM_Name3_HR);
	labelMap.set('AGN_OAM_Specialty_Allergan_1',  AGN_OAM_Specialty_Allergan_1);
	labelMap.set('AGN_OAM_First_Name_1',  AGN_OAM_First_Name_1);
	labelMap.set('AGN_OAM_Last_Name_1',  AGN_OAM_Last_Name_1);
	labelMap.set('AGN_OAM_Company_Name_SoldTo_PH_VP_Address',  AGN_OAM_Company_Name_SoldTo_PH_VP_Address);
	labelMap.set('AGN_OAM_RPPS',  AGN_OAM_RPPS);
	labelMap.set('AGN_OAM_AAF_Signed',  AGN_OAM_AAF_Signed);
	labelMap.set('AGN_OAM_VAT_Number_Registered',  AGN_OAM_VAT_Number_Registered);
	labelMap.set('AGN_OAM_Date_of_Birth',  AGN_OAM_Date_of_Birth);
	labelMap.set('AGN_OAM_Professional_Designation',  AGN_OAM_Professional_Designation);
	labelMap.set('AGN_OAM_Nome_Direttore_Sanitario',  AGN_OAM_Nome_Direttore_Sanitario);
	labelMap.set('AGN_OAM_VAT_Number_4',  AGN_OAM_VAT_Number_4);
	labelMap.set('AGN_OAM_Service_code',  AGN_OAM_Service_code);
	labelMap.set('AGN_OAM_Registration_License_Number_1',  AGN_OAM_Registration_License_Number_1);
	labelMap.set('AGN_OAM_Contact_Affiliation',  AGN_OAM_Contact_Affiliation);
	labelMap.set('AGN_OAM_Product_Interest_SubHeading',  AGN_OAM_Product_Interest_SubHeading);
	labelMap.set('AGN_OAM_Confirmation_AAF_Date',  AGN_OAM_Confirmation_AAF_Date);
	labelMap.set('AGN_Consent_to_Email',  AGN_Consent_to_Email);
	labelMap.set('AGN_Consent_to_Contact',  AGN_Consent_to_Contact);
	labelMap.set('AGN_Consent_to_Mail',  AGN_Consent_to_Mail);
	labelMap.set('AGN_OAM_Consent_to_Phone',  AGN_OAM_Consent_to_Phone);
	labelMap.set('AGN_OAM_Account_Status',  AGN_OAM_Account_Status);
	labelMap.set('AGN_Sub_Speciality_Allergan',  AGN_Sub_Speciality_Allergan);
	labelMap.set('AGN_OAM_Graduation_Year',  AGN_OAM_Graduation_Year);
	labelMap.set('AGN_GCSP_Brick',  AGN_GCSP_Brick);
	labelMap.set('AGN_Appt_Required',  AGN_Appt_Required);
	labelMap.set('AGN_Receiptionist_Email',  AGN_Receiptionist_Email);
	labelMap.set('AGN_Receptionist_Name',  AGN_Receptionist_Name);
	labelMap.set('AGN_OAM_Phone_2',  AGN_OAM_Phone_2);
	labelMap.set('AGN_OAM_Body_Street',  AGN_OAM_Body_Street);
	labelMap.set('AGN_OAM_Body_Number',  AGN_OAM_Body_Number);
	labelMap.set('AGN_OAM_Body_Address_Line_2',  AGN_OAM_Body_Address_Line_2);
	labelMap.set('AGN_OAM_Body_Address_Line_3',  AGN_OAM_Body_Address_Line_3);
	labelMap.set('AGN_OAM_Body_City',  AGN_OAM_Body_City);
	labelMap.set('AGN_OAM_Body_County',  AGN_OAM_Body_County);
	labelMap.set('AGN_OAM_Middle_Name',  AGN_OAM_Middle_Name);
	labelMap.set('AGN_OAM_Body_DOB',  AGN_OAM_Body_DOB);
	labelMap.set('AGN_OAM_Body_Gender',  AGN_OAM_Body_Gender);
	labelMap.set('AGN_OAM_Body_PurposeOfBusiness',  AGN_OAM_Body_PurposeOfBusiness);
	labelMap.set('AGN_OAM_Body_Preferred',  AGN_OAM_Body_Preferred);
	labelMap.set('AGN_Physician_Registration_Reference',  AGN_Physician_Registration_Reference);
	labelMap.set('AGN_OAM_Body_Mobile',  AGN_OAM_Body_Mobile);
	labelMap.set('AGN_OAM_Body_Phone',  AGN_OAM_Body_Phone);
	labelMap.set('AGN_OAM_Body_Email',  AGN_OAM_Body_Email);
	labelMap.set('AGN_OAM_Body_Email2',  AGN_OAM_Body_Email2);
	labelMap.set('AGN_OAM_State_Registration',  AGN_OAM_State_Registration);
	labelMap.set('AGN_OAM_CPF_CNPJ',  AGN_OAM_CPF_CNPJ);
	labelMap.set('AGN_OAM_CRM_CRO',  AGN_OAM_CRM_CRO);
	labelMap.set('AGN_OAM_CRM_CRO_UF',  AGN_OAM_CRM_CRO_UF);
	labelMap.set('AGN_OAM_Body_Name',  AGN_OAM_Body_Name);
	labelMap.set('AGN_OAM_Body_Surname',  AGN_OAM_Body_Surname);
	labelMap.set('AGN_OAM_Body_Title',  AGN_OAM_Body_Title);
	labelMap.set('AGN_OAM_Body_PostalCode',  AGN_OAM_Body_PostalCode);
	labelMap.set('AGN_OAM_Body_BusinessPracticeName',  AGN_OAM_Body_BusinessPracticeName);
	labelMap.set('AGN_OAM_Body_DepartmentName',  AGN_OAM_Body_DepartmentName);
	labelMap.set('AGN_OAM_Body_Address',  AGN_OAM_Body_Address);
	labelMap.set('AGN_OAM_Communication_Contact',  AGN_OAM_Communication_Contact);
	labelMap.set('AGN_OAM_Address',  AGN_OAM_Address);
	labelMap.set('AGN_OAM_Business_Unit',  AGN_OAM_Business_Unit);
	labelMap.set('AGN_OAM_Street_Name',  AGN_OAM_Street_Name);
	labelMap.set('AGN_OAM_House_Number',  AGN_OAM_House_Number);
	labelMap.set('AGN_OAM_Body_State',  AGN_OAM_Body_State);
	labelMap.set('AGN_OAM_BussinessEmail',  AGN_OAM_BussinessEmail);
	labelMap.set('AGN_OAM_Surname',  AGN_OAM_Surname);
	labelMap.set('AGN_OAM_Address_Line_2',  AGN_OAM_Address_Line_2);
	labelMap.set('AGN_OAM_Postal_Code',  AGN_OAM_Postal_Code);
	labelMap.set('AGN_OAM_Suburb',  AGN_OAM_Suburb);
	labelMap.set('AGN_OAM_Product_Interest_ANZ',  AGN_OAM_Product_Interest_ANZ);
	labelMap.set('AGN_OAM_Additional_Phone',  AGN_OAM_Additional_Phone);
	labelMap.set('AGN_OAM_Prescribing_doctor_Account',  AGN_OAM_Prescribing_doctor_Account);
	labelMap.set('AGN_OAM_NZBN_Number',  AGN_OAM_NZBN_Number);
	labelMap.set('AGN_OAM_Comments',  AGN_OAM_Comments);
	labelMap.set('AGN_OAM_Name',  AGN_OAM_Name);
	labelMap.set('AGN_OAM_Street_Number',  AGN_OAM_Street_Number);
	labelMap.set('AGN_OAM_Company_Number',  AGN_OAM_Company_Number);
	labelMap.set('AGN_OAM_Bussiness_Name',  AGN_OAM_Bussiness_Name);
	labelMap.set('AGN_OAM_Account_Changes',  AGN_OAM_Account_Changes);
	labelMap.set('AGN_OAM_Portal_Department_Name',  AGN_OAM_Portal_Department_Name);
	labelMap.set('AGN_OAM_Bussiness_Name_ShipTo',  AGN_OAM_Bussiness_Name_ShipTo);
	labelMap.set('AGN_OAM_Bussiness_Name_BillTo',  AGN_OAM_Bussiness_Name_BillTo);
	labelMap.set('AGN_OAM_Prescribing_Dr_Registration_Number',  AGN_OAM_Prescribing_Dr_Registration_Number);
	labelMap.set('AGN_OAM_Prescribing_Dr_HPI_Number',  AGN_OAM_Prescribing_Dr_HPI_Number);
	labelMap.set('AGN_OAM_Business_Name_Reference1',  AGN_OAM_Business_Name_Reference1);
	labelMap.set('AGN_OAM_Contact_Name_Reference1',  AGN_OAM_Contact_Name_Reference1);
	labelMap.set('AGN_OAM_Phone_Reference1',  AGN_OAM_Phone_Reference1);
	labelMap.set('AGN_OAM_Email_Reference1',  AGN_OAM_Email_Reference1);
	labelMap.set('AGN_OAM_Overseeing_accountID',  AGN_OAM_Overseeing_accountID);
	labelMap.set('AGN_OAM_Suite',  AGN_OAM_Suite);
	labelMap.set('AGN_OAM_Registred_Home_Address',  AGN_OAM_Registred_Home_Address);
	labelMap.set('AGN_OAM_ACCOUNT_OWNER_EMAIL',  AGN_OAM_ACCOUNT_OWNER_EMAIL);
	labelMap.set('AGN_OAM_CONSENT_TO_ALBERTA',  AGN_OAM_CONSENT_TO_ALBERTA);
	labelMap.set('AGN_OAM_Physician_License_Number',  AGN_OAM_Physician_License_Number);
	labelMap.set('AGN_OAM_Bussiness_Registration_Number',  AGN_OAM_Bussiness_Registration_Number);
	labelMap.set('AGN_OAM_Business_Name_Reference2',  AGN_OAM_Business_Name_Reference2);
	labelMap.set('AGN_OAM_Contact_Name_Reference2',  AGN_OAM_Contact_Name_Reference2);
	labelMap.set('AGN_OAM_Fax_Reference2',  AGN_OAM_Fax_Reference2);
	labelMap.set('AGN_OAM_Fax_Reference1',  AGN_OAM_Fax_Reference1);
	labelMap.set('AGN_OAM_Phone_Reference2',  AGN_OAM_Phone_Reference2);
	labelMap.set('AGN_OAM_Hospital_Name',  AGN_OAM_Hospital_Name);
	labelMap.set('AGN_OAM_Hospital_Phone',  AGN_OAM_Hospital_Phone);
	labelMap.set('AGN_OAM_Doctors_Name',  AGN_OAM_Doctors_Name);
	labelMap.set('AGN_OAM_Primary_Pharmacist_Email',  AGN_OAM_Primary_Pharmacist_Email);
	labelMap.set('AGN_OAM_Primary_Physician_Phone',  AGN_OAM_Primary_Physician_Phone);
	labelMap.set('AGN_OAM_Primary_Physician_Email',  AGN_OAM_Primary_Physician_Email);
	labelMap.set('AGN_OAM_Primary_Pharmacist_Name',  AGN_OAM_Primary_Pharmacist_Name);
	labelMap.set('AGN_OAM_VERIFIED_ADDRESS',  AGN_OAM_VERIFIED_ADDRESS);
	labelMap.set('AGN_OAM_Doctors_SurName',  AGN_OAM_Doctors_SurName);
	labelMap.set('AGN_OAM_License_Number',  AGN_OAM_License_Number);
	labelMap.set('AGN_OAM_Primary_Physician_Name',  AGN_OAM_Primary_Physician_Name);
	labelMap.set('AGN_OAM_Pharmacy_license_number',  AGN_OAM_Pharmacy_license_number);
	labelMap.set('AGN_OAM_Primary_Pharmacist_Phone',  AGN_OAM_Primary_Pharmacist_Phone);
	labelMap.set('AGN_OAM_Hospital_Email',  AGN_OAM_Hospital_Email);
	labelMap.set('AGN_OAM_Business_Name_Reference3',  AGN_OAM_Business_Name_Reference3);
	labelMap.set('AGN_OAM_Email_Reference2',  AGN_OAM_Email_Reference2);
	labelMap.set('AGN_OAM_Contact_Name_Reference3',  AGN_OAM_Contact_Name_Reference3);
	labelMap.set('AGN_OAM_Phone_Reference3',  AGN_OAM_Phone_Reference3);
	labelMap.set('AGN_OAM_Email_Reference3',  AGN_OAM_Email_Reference3);
	labelMap.set('AGN_OAM_Consignment_Authorized',  AGN_OAM_Consignment_Authorized);
	labelMap.set('AGN_OAM_First_Name_CS',  AGN_OAM_First_Name_CS);
	labelMap.set('AGN_OAM_Last_Name_CS',  AGN_OAM_Last_Name_CS);
	labelMap.set('AGN_OAM_Email_CS',  AGN_OAM_Email_CS);
	labelMap.set('AGN_OAM_Province_CS',  AGN_OAM_Province_CS);
	labelMap.set('AGN_OAM_Salutation_CS',  AGN_OAM_Salutation_CS);
	labelMap.set('AGN_OAM_Phone_CS',  AGN_OAM_Phone_CS);
	labelMap.set('AGN_OAM_Name_1',  AGN_OAM_Name_1);
	labelMap.set('AGN_OAM_Name_2',  AGN_OAM_Name_2);
	labelMap.set('AGN_OAM_State2',  AGN_OAM_State2);
	labelMap.set('AGN_OAM_Company_Name_Medecian_DN',  AGN_OAM_Company_Name_Medecian_DN);
	labelMap.set('AGN_GCSP_RegistrationLicense_No',  AGN_GCSP_RegistrationLicense_No);
	labelMap.set('AGN_Article_23_Text_2',  AGN_Article_23_Text_2);
	labelMap.set('AGN_OAM_NameHeadIsPharmasist',  AGN_OAM_NameHeadIsPharmasist);
	labelMap.set('AGN_OAM_Company_Name_1_Bill_To_CL',  AGN_OAM_Company_Name_1_Bill_To_CL);
	labelMap.set('AGN_OAM_Big_Number',  AGN_OAM_Big_Number);
	labelMap.set('AGN_OAM_VAT_Reg_No',  AGN_OAM_VAT_Reg_No);
	labelMap.set('AGN_OAM_Wholesaler_Distributor_Licence',  AGN_OAM_Wholesaler_Distributor_Licence);
	labelMap.set('AGN_OAM_Reference_1',  AGN_OAM_Reference_1);
	labelMap.set('AGN_OAM_Reference_2',  AGN_OAM_Reference_2);
	labelMap.set('AGN_OAM_Reference_3',  AGN_OAM_Reference_3);
	labelMap.set('AGN_OAM_ABN_Number',  AGN_OAM_ABN_Number);
	labelMap.set('AGN_OAM_Prescribing_Doc_First_Name',  AGN_OAM_Prescribing_Doc_First_Name);
	labelMap.set('AGN_OAM_Prescribing_Doc_Middle_Name',  AGN_OAM_Prescribing_Doc_Middle_Name);
	labelMap.set('AGN_OAM_Prescribing_Doc_Last_Name',  AGN_OAM_Prescribing_Doc_Last_Name);
	labelMap.set('AGN_OAM_Prescribing_Doc_Email',  AGN_OAM_Prescribing_Doc_Email);
	labelMap.set('AGN_OAM_Prescribing_Doc_Phone',  AGN_OAM_Prescribing_Doc_Phone);
	labelMap.set('AGN_OAM_Prescribing_Dr_AHPRA_Registration_Number',  AGN_OAM_Prescribing_Dr_AHPRA_Registration_Number);
	labelMap.set('AGN_OAM_Nurse_Practitioners_AHPRA_Registration_Number',  AGN_OAM_Nurse_Practitioners_AHPRA_Registration_Number);
	labelMap.set('AGN_OAM_Nurse_Practitioners_Registration_Number',  AGN_OAM_Nurse_Practitioners_Registration_Number);
	labelMap.set('AGN_OAM_Nurse_Practitioners_HPI_Number',  AGN_OAM_Nurse_Practitioners_HPI_Number);
    return labelMap;
};
export default {
    getCustomLable
}