/* --------------------------------------------------------------------------------------------------
* @author         Cognizant   
* @modifiedBy     Preeti Achary   
* @createdBy      Preeti Achary   
* @version        1.0
* @created        Nov14'2019
* @modified       
* @testClass             
* --------------------------------------------------------------------------------------------------
* @changes
* vX.X            
* YYYY-MM-DD      
* -------------------------------------------------------------------------------------------------+
*/
public without sharing class AGN_GDPR_ConstantUtility {

    public final static String CCPA_AGN = 'CCPA_AGN';
    public final static String ASSET_REG_OBJECT_API = 'Asset_Register_AGN__c';
    public final static String AGN_GDPR_Case_DPO = 'AGN_DSRM_Users';
    public final static String SYSTEM_ADMIN_PROFILE = 'System Administrator';
    public final static String CCPA = 'CCPA';
    public final static String GDPR= 'GDPR';
    public final static String DATASUB_ACCESSREQ= 'Data Subject Access Request';
    public final static String CCPA_ACCESSREQ= 'IR-USLPO';
}