//public class AGN_FlowEmailWrapper {
public without sharing class AGN_FlowEmailWrapper {  /* added without sharing for Spring'21 Release Updates */     
    @AuraEnabled @InvocableVariable public String emailId;
    @AuraEnabled @InvocableVariable public String sobjId;  
    @AuraEnabled @InvocableVariable public String accName;
    @AuraEnabled @InvocableVariable public String channellabel; 
    @AuraEnabled @InvocableVariable public String MCountrycode;
    @AuraEnabled @InvocableVariable public String MLangcode; 
    @AuraEnabled @InvocableVariable public String OptType;
}