// This class is created refrain use of Hardcodes values in different apex controllers.All Hardcoded values used in AMI project should be defined here
// Author - Cognizant
// Created Date - 11/12/2019
// Last Modified By - Cognizant
public class AGN_AMI_SC_Static_Labels {
    public static String attendeeStatusCancelled = 'Cancelled';
	public static String attendeeStatusInvited = 'Invited';
    public static String attendeeStatusRegistered = 'Registered';
    public static String attendeeStatusAccepted = 'Accepted';
    public static String attendeeStatusAttended = 'Attended';
    public static String meetingStatusLive = 'Live';
    public static String meetingStatusRecorded = 'Recorded';
    public static String meetingTypePublic = 'Public';
    public static String meetingTypePrivate = 'Private';
    public static String specialityCare = 'Specialty Care';
    public static String medicalAesthetics = 'Medical Aesthetics';
    public static String CspLitePortal='CspLitePortal';
    public static String ChatterNetworks='ChatterNetworks';
    public static String New_AMI_AGN='New_AMI_AGN';
    public static String AMI_SC_Customer_Community='AMI SC Customer Community';
    public static String GB='GB';
    public static String YZ='YZ';
    public Static String en_GB='en_GB';
    public Static String en_US='en_US';
    public Static String success='success';
    public Static String Guest='Guest';
}