public class MDChilObjectFieldConfig {
	@AuraEnabled
    public static string DeveloperName {get;set;}
    
    @AuraEnabled
    public static string FieldAPIName {get;set;}
    
    @AuraEnabled
    public static string DisplayLabel {get;set;}
    
    @AuraEnabled
    public static Boolean Required {get;set;}
    
    @AuraEnabled
    public static String QuickHelpText {get;set;}
    
    @AuraEnabled
    public static Boolean IsHidden {get;set;}
    
    @AuraEnabled
    public static String DefaultValue {get;set;}
}