/*******************************************************************************
* @author         :    Wrapper class for 
* @date           :    March 2019 
* @description    :    
* @Revisions      :    
*******************************************************************************/
public class MDObjectFieldInfoWrapper 
{
	@AuraEnabled
    public String FieldLabel {get;set;}
    
    @AuraEnabled
    public String FieldAPIName {get;set;}
}